name: 'David Ollerhead'
highlighter: pygments
permalink: pretty

asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  # display_path: nil       # Default = nil
  gzip: false             # Default = false
