name: 'David Ollerhead'
pygments: true
permalink: pretty

asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  # display_path: nil       # Default = nil
  gzip: true             # Default = false